declare module "*.scss";
declare module "*.svg";
declare module "*.png";
declare module "*.gif";
declare module "*.jpg";
declare module "*.sol";
declare module "*.webm";
declare module "*.mp4";
declare module "*/googleAnalitycs.js";
